require('plugin')
require('config')
require('colorscheme')
require('keysmapping')
require('providers')
require('treesitter')
require('ale')
require('coc')
vim.cmd('source $HOME/.config/nvim/vimscript/coc/config.vim')
require('lightline')
require('nerdtree')
require('telescopes')
require('rust')
require('fugitives')
require('gitsignify')
vim.cmd('source $HOME/.config/nvim/vimscript/startifies/config.vim')
require('tagbars')
-- vim.cmd('source $HOME/.config/nvim/vimscript/tagbar/config.vim')
require('floatterms')
require('vemmet')
require('javascript')
require('python')
require('go')
require('vcsv')
require('commentaries')
require('markdown')



