
-- general
require('plugins')
require('config.global')
require('config.user')
require('config')
require('config.keymappings')
require('config.colorscheme')

-- extensions
require('extensions')
require('extensions.autopairs')
require('extensions.barbar')
require('extensions.colorizer')
require('extensions.dash')
require('extensions.db-completion')
require('extensions.devicon')
require('extensions.doge')
require('extensions.easy-align')
require('extensions.emmet')
require('extensions.formatters')
require('extensions.fugitive')
require('extensions.galaxy-line')
require('extensions.git-blame')
require('extensions.git-ui')
require('extensions.indent')
require('extensions.markdown')
require('extensions.signify')
require('extensions.tagbar')
require('extensions.telescope')
require('extensions.tree')
require('extensions.treesitter')
require('extensions.ts-rainbow')
require('extensions.whichkey')
-- require('extensions.zen-mode')
require('extensions.terminal')

-- lsp config
require('lsp')
require('lsp.completion')  -- autocomplete

-- lsp server
require('lsp.bash')
require('lsp.clangd')
require('lsp.cmake')
require('lsp.css')
require('lsp.docker')
require('lsp.go')
require('lsp.html')
require('lsp.json')
require('lsp.python')
require('lsp.rust')
require('lsp.tsserver')
require('lsp.vim')
-- require('lsp.vue-lsp')
require('lsp.yaml')
require('lsp.lua')
require('lsp.svelte')
require('lsp.tailwindcss')

