source $HOME/.config/nvim/plugin/plugs.vim
source $HOME/.config/nvim/plugin-config/general.vim
source $HOME/.config/nvim/plugin-config/ale.vim
source $HOME/.config/nvim/plugin-config/py.vim
source $HOME/.config/nvim/plugin-config/js.vim
source $HOME/.config/nvim/plugin-config/coc.vim
source $HOME/.config/nvim/plugin-config/md.vim
source $HOME/.config/nvim/plugin-config/others.vim
source $HOME/.config/nvim/plugin-config/go.vim
source $HOME/.config/nvim/plugin-config/rust.vim
source $HOME/.config/nvim/plugin-config/mapping.vim
source $HOME/.config/nvim/plugin-config/tagbar.vim
source $HOME/.config/nvim/plugin-config/line.vim
source $HOME/.config/nvim/plugin-config/fzf.vim
source $HOME/.config/nvim/plugin-config/nerdtree.vim
source $HOME/.config/nvim/plugin-config/emmet.vim
source $HOME/.config/nvim/plugin-config/theme.vim
source $HOME/.config/nvim/plugin-config/treesitter.vim
source $HOME/.config/nvim/plugin-config/fugitive.vim
source $HOME/.config/nvim/plugin-config/gitsign.vim
source $HOME/.config/nvim/plugin-config/floatterm.vim
source $HOME/.config/nvim/plugin-config/startify.vim
