require('plugin')
require('config')
require('colorscheme')
require('keysmapping')
vim.cmd('source $HOME/.config/nvim/plugin/plugs.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/general.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/ale.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/py.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/js.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/coc.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/md.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/others.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/go.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/rust.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/mapping.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/tagbar.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/line.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/fzf.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/nerdtree.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/emmet.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/theme.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/treesitter.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/fugitive.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/gitsign.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/floatterm.vim')
vim.cmd('source $HOME/.config/nvim/plugin-config/startify.vim')
