local lsputils = require("lsp.utils")
local Path = require("plenary.path")

local function get_root(fname)
    if not fname or fname == "" or type(fname) == "number" then
        return vim.fn.getcwd()
    end

    -- Ensure we have an absolute path
    if not vim.startswith(fname, "/") then
        fname = vim.fn.fnamemodify(fname, ":p")
    end

    local path = vim.fs.dirname(fname)
    local primary_root = vim.fs.find({ ".venv", ".git", "Dockerfile" }, { upward = true, path = path })[1]
    if primary_root then
        return vim.fs.dirname(primary_root)
    end

    local secondary_root = vim.fs.find({ "pyproject.toml", "requirements.txt", "uv.lock" }, { upward = true, path = path })[1]
    if secondary_root then
        return vim.fs.dirname(secondary_root)
    end

    -- Fallback to file's directory instead of cwd
    return path or vim.fn.getcwd()
end

local function find_extra_paths(root_dir)
    local root_path = Path:new(root_dir)
    return {
        tostring(root_path),
        tostring(root_path:joinpath("odoo")),
        tostring(root_path:joinpath("odoo/addons")),
        tostring(root_path:joinpath("my_addons")),
        tostring(root_path:joinpath("abenla-erp/custom-addons")),
    }
end

local function _python_path(dir)
    if not dir then dir = vim.fn.getcwd() end
    local venv_python = dir .. "/.venv/bin/python"
    if vim.fn.executable(venv_python) == 1 then
        return venv_python
    end
    return vim.fn.exepath("python3") or "python"
end

local function setup()
    local capabilities = require("lsp").capabilities and require("lsp").capabilities() or vim.lsp.protocol.make_client_capabilities()

    vim.api.nvim_create_autocmd("FileType", {
        pattern = "python",
        callback = function(ev)
            -- Get the file path from buffer name instead of ev.file
            local bufname = vim.api.nvim_buf_get_name(ev.buf)
            if bufname == "" then
                bufname = vim.fn.getcwd()
            end

            local root_dir = get_root(bufname)

            -- Ensure root_dir is absolute path
            if not vim.startswith(root_dir, "/") then
                root_dir = vim.fn.fnamemodify(root_dir, ":p"):gsub("/$", "")
            end

            -- DEBUG: remove these lines after confirming LSP works
            -- vim.notify(string.format("[PY-DBG] buf=%s\n  root=%s\n  python=%s",
            --     bufname, root_dir, _python_path(root_dir)), vim.log.levels.INFO)

            -- Configuration for pyrefly
            local pyrefly_cmd = vim.fn.stdpath("data") .. "/mason/bin/pyrefly"
            if vim.fn.executable(pyrefly_cmd) ~= 1 then
                 pyrefly_cmd = "pyrefly" -- fallback to path
            end

            -- Build pyrefly-native search paths for Odoo
            local search_paths = find_extra_paths(root_dir)
            local python_path = _python_path(root_dir)

            -- Build site-package-path from venv if available
            local site_pkg_path = {}
            local venv_dir = root_dir .. "/.venv"
            if vim.fn.isdirectory(venv_dir) == 1 then
                local glob = vim.fn.glob(venv_dir .. "/lib/python*/site-packages")
                if glob ~= "" then
                    for p in glob:gmatch("[^\n]+") do
                        table.insert(site_pkg_path, p)
                    end
                end
            end

            -- Ensure pyrefly.toml exists at project root for Odoo projects
            local pyrefly_toml = root_dir .. "/pyrefly.toml"
            if vim.fn.filereadable(pyrefly_toml) ~= 1 and vim.fn.isdirectory(venv_dir) == 1 then
                local toml_lines = {
                    "# Auto-generated by Neovim for Odoo development",
                    'project-includes = ["**/*.py"]',
                    'project-excludes = ["**/node_modules", "**/__pycache__", "**/*venv/**", "**/.[!/.]*/**"]',
                    "",
                    "search-path = [",
                }
                for _, sp in ipairs(search_paths) do
                    table.insert(toml_lines, string.format('    "%s",', sp))
                end
                table.insert(toml_lines, "]")
                table.insert(toml_lines, "")

                if #site_pkg_path > 0 then
                    table.insert(toml_lines, "site-package-path = [")
                    for _, sp in ipairs(site_pkg_path) do
                        table.insert(toml_lines, string.format('    "%s",', sp))
                    end
                    table.insert(toml_lines, "]")
                    table.insert(toml_lines, "")
                end

                table.insert(toml_lines, string.format('python-interpreter-path = "%s"', python_path))
                table.insert(toml_lines, 'python-platform = "linux"')
                table.insert(toml_lines, "")
                table.insert(toml_lines, "# Suppress noisy errors common in Odoo's dynamic code")
                table.insert(toml_lines, "[errors]")
                table.insert(toml_lines, "# missing-import = false")
                table.insert(toml_lines, "")

                vim.fn.writefile(toml_lines, pyrefly_toml)
                -- vim.notify("[pyrefly] Generated pyrefly.toml at " .. root_dir, vim.log.levels.INFO)
            end

            local pyrefly_client_id = vim.lsp.start({
                name = "pyrefly",
                cmd = { pyrefly_cmd, "lsp" },
                root_dir = root_dir,
                -- Pyrefly reads its config from pyrefly.toml at root_dir.
                -- No Pyright-style settings needed.
                settings = {},
                on_attach = function(client, bufnr)
                    require("lsp").common_on_attach(client, bufnr)
                    -- Explicitly enable inlay hints if supported
                    if client.server_capabilities.inlayHintProvider then
                        vim.lsp.inlay_hint.enable(true, { bufnr = bufnr })
                    end
                end,
                capabilities = capabilities,
            }, {
                bufnr = ev.buf,
                reuse_client = function(client, conf)
                    return client.name == conf.name and client.config.root_dir == conf.root_dir
                end
            })

            if not pyrefly_client_id then
                vim.notify("Failed to start pyrefly", vim.log.levels.ERROR)
            end

            -- Configuration for ruff
            local ruff_cmd = vim.fn.stdpath("data") .. "/mason/bin/ruff"
            if vim.fn.executable(ruff_cmd) ~= 1 then
                ruff_cmd = "ruff"
            end

            local ruff_client_id = vim.lsp.start({
                name = "ruff",
                cmd = { ruff_cmd, "server", "--preview" },
                root_dir = root_dir,
                on_attach = function(client, bufnr)
                    if client.name == "ruff" then
                        -- Disable hover from ruff in favor of pyrefly
                        client.server_capabilities.hoverProvider = false
                    end
                    require("lsp").common_on_attach(client, bufnr)
                end,
                capabilities = capabilities,
            }, {
                bufnr = ev.buf,
                reuse_client = function(client, conf)
                    return client.name == conf.name and client.config.root_dir == conf.root_dir
                end
            })
            
             if not ruff_client_id then
                vim.notify("Failed to start ruff", vim.log.levels.ERROR)
            end
        end,
    })
end

return {
    _python_path = _python_path,
    setup = setup,
}
